name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ feature_Move, master ]
  pull_request:
    branches: [ feature_Move, master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup test enviroment
      run: dotnet tool install --global dotnet-coverage
    - name: Test
      run: dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          token: 94f4aaac-cd56-43d3-856f-e52442467054
